# This is a basic workflow to help you get started with Actions

name: Flutter build apk

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 21 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.11'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build apk --flavor development --debug
      
      - name: Save result
        uses: actions/upload-artifact@v2
        with:
          name: compiled-flutter-code
          path: build/app/outputs/flutter-apk/app-development-debug.apk


# You may pin to the exact commit or the version.
# uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
